### ISSUE TITLE
the list of cases that can not parse 'Appellant name' and  'Respondent name'

### ISSUE THREAD

**Issue by mcqueen1987** [openlawnz/openlawnz-parsers#35]
we need to talk about those case, how to get 'Appellant name' and  'Respondent name' or ignore it.

**Comment by mcqueen1987** [comment]
IN THE HIGH COURT OF NEW ZEALAND
CHRISTCHURCH REGISTRY
CIV-2014-476-000046
[2014] NZHC 1768
IN THE MATTER OF
Section 51 of the Trustee Act 1956
AND
IN THE MATTER OF
an application by ALEXANDER JAMES STEWART of Timaru, Retired, for an
order appointing trustees to the STRATHAVEN FAMILY TRUST
Date:
29 July 2014
Appearances:
K A Thomas for Applicant
Judgment:
29 July 2014
JUDGMENT OF DUNNINGHAM J`

**Comment by mcqueen1987** [comment]
`failed to parse 13405: appellant
IN THE HIGH COURT OF NEW ZEALAND
NEW PLYMOUTH REGISTRY
CIV-2013-443-259
[2014] NZHC 1632
IN THE MATTER OF
the Wills Act 2007 and the Administration Act 1969
IN THE MATTER OF
the Estate of Norman Rob Campbell
Hearing:
On the papers
Counsel:
G F Kelly for applicants
S Kinsler as amicus curiae
Judgment:
11 July 2014
JUDGMENT OF MACKENZIE J
I direct that the delivery time of this judgment is 3 pm on the 11th day of July 2014.
Solicitors:	Welsh McCarthy, Hawera
Crown Law Office, Wellington
Re Campbell (deceased) [2014] NZHC 1632 [11 July 2014]`

**Comment by mcqueen1987** [comment]
failed to parse 12757: appellant
IN THE HIGH COURT OF NEW ZEALAND
WELLINGTON REGISTRY
CIV-2014-485-11228
[2014] NZHC 2303
IN THE ESTATE OF
HAROLD HORACE MEECHAM of
Rotorua, deceased
Hearing:
On the papers
Counsel:
P M Lines for applicants
Judgment:

**Comment by mcqueen1987** [comment]
failed to parse 12775: appellant
IN THE HIGH COURT OF NEW ZEALAND
TIMARU REGISTRY
CIV-2014-485-7172
[2014] NZHC 2266
IN THE ESTATE OF
AVERIL JUNE JOHNSTONE formerly of Geraldine, retired, late of Timaru
Deceased
In Chambers:
On papers
Judgment:
18 September 2014
JUDGMENT OF THE HON JUSTICE KÓS

**Comment by mcqueen1987** [comment]
IN THE HIGH COURT OF NEW ZEALAND
WELLINGTON REGISTRY
CIV-2014-485-6780
[2014] NZHC 1484
IN THE MATTER OF
an application under Section 14 of the Wills Act 2007
IN THE ESTATE OF
POOTHATHAMBY AYATHURAI SUBRAMANIAM
Hearing:
On the papers
Counsel:
R D Ganda
Judgment:
30 June 2014
JUDGMENT OF MACKENZIE J

**Comment by mcqueen1987** [comment]
IN THE HIGH COURT OF NEW ZEALAND AUCKLAND REGISTRY
CIV2006-404-1164


IN THE MATTER OF	the Insolvency Act 1967
AND IN THE MATTER OF The bankruptcy of HUSAIN KHALIL
EBRAHIM Al SAFFAF


CINDY SIEW-LI YEOH C/- LEVEL 6, 48 GREYS AVE AUCKLAND, COMPANY DIERCTOR AND COSMOS FARMS LIMITED (FORMERLY AMITA ENTERPRISE LIMITED)
Judgment Creditors

AND
HUSAIN KHALIL EBRAHIM AL SAFFAF
Judgment Debtor


Hearing:	16 June 2006

Appearances: G P Blanchard for Judgment Creditors G W Hall for Judgment Debtor

Judgment:	21 June 2006 at 4:45 pm

JUDGMENT OF ASSOCIATE JUDGE JP DOOGUE















Solicitors:
Kensington Swan, Private Bag 92101, Auckland Buddle Findlay, PO Box 1433, Auckland



HKE AL SAFFAF AND C SIEW & ANOR HC AK CIV2006-404-1164 21 June 2006

**Comment by mcqueen1987** [comment]
IN THE HIGH COURT OF NEW ZEALAND AUCKLAND REGISTRY
CIV 2009-404-1217

UNDER		section 239AT of the Companies Act 1993, Part 15A of the Companies Act 1993 and Part 19 of the High Court Rules

IN THE MATTER OF	an application under s 239AT of the
Companies Act 1993 for an order extending the convening period by which the administrators must convene the watershed meeting

NYLEX (NEW ZEALAND) LIMITED (ADMINISTRATORS APPOINTED AND IN RECEIVERSHIP)

NYLEX ENGINEERING SYSTEMS LIMITED (ADMINISTRATORS APPOINTED AND IN RECEIVERSHIP)


Hearing:	(on the papers)

Counsel:	B Gustafson and M Broad for Applicants Judgment:	10 March 2009
Reasons:	11 March 2009

REASONS FOR JUDGMENT OF HEATH J












Solicitors:
Kensington Swan, Private Bag 92101, Auckland

NYLEX (NEW ZEALAND) LIMITED (ADMINISTRATORS APPOINTED AND IN RECEIVERSHIP) AND ANOR HC AK CIV 2009-404-1217 10 March 2009


Application and disposition

**Comment by strum3nt** [comment]
Good points. Current logic won't deal with these ones. I suggest if no match in a case for existing logic, then try the following logic (as a backup only - use the main logic if possible first):

- Look at the text after the **last** "IN THE MATTER OF" or "IN THE ESTATE OF" or "IN THE MATTER OF an application by". The name after those words is the party name.
- Please test whether the following name is consistently in ALL CAPS (that way you could easily find the limits of the name and strip out the irrelevant data - if possible to discard things like "formerly of Geraldine" then discard, if not possible, then that's ok). 
- If all caps are not consistent, then alternative method is that party name begins after the phrase and runs until the **first** occurrence of the word "of", "Hearing", "Appearances", "Deceased", or "Judgment". Maybe you will find some other words as well. Perhaps we should build this logic in as backup in case ALL CAPS is very long or does not work? (Or could do both method, compare the two, and take the shorter string)
- This should provide one name string for examples 1, 2, 3, 4, 5 above. That one name should be listed as a new party type (not applicant/respondent/appellant/plaintiff). New party type = "Re". This is because the case is not between two parties, it is just 'about' one person.

Example 6 above I am not sure how to fix without making an error in examples 1 - 5. That one is similar in that the case is "about" NYLEX (NEW ZEALAND) LIMITED and NYLEX ENGINEERING SYSTEMS LIMITED. But how to extract only that text (or even just one of them) is the question. I think my only guess is to use ALL CAPS:

- Look for last "IN THE MATTER OF" then look for next words in all caps, until all caps ends.
- Words in all caps = party type "Re"

In above example that would result in the party type Re = "NYLEX (NEW ZEALAND) LIMITED (ADMINISTRATORS APPOINTED AND IN RECEIVERSHIP) NYLEX ENGINEERING SYSTEMS LIMITED (ADMINISTRATORS APPOINTED AND IN RECEIVERSHIP)". This is untidy, but ultimately acceptable I think as this one is a very strange case. 

If ALL CAPS does not work, then I think this example 6 is an edge case with no party name. If < 0.01 have no party name possible, that is ok.
